# Generated by Django 3.2.15 on 2022-08-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('gender', models.CharField(max_length=30, verbose_name='性别')),
                ('occupation', models.CharField(max_length=30, verbose_name='职业')),
                ('fans', models.CharField(max_length=255, verbose_name='粉丝列表')),
                ('fans_num', models.IntegerField(verbose_name='粉丝数')),
                ('Attentions', models.CharField(max_length=255, verbose_name='关注列表')),
                ('Attentions_num', models.IntegerField(verbose_name='关注数')),
                ('Image', models.ImageField(upload_to='', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
    ]
