# Generated by Django 3.2.15 on 2022-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Attentions',
            field=models.CharField(max_length=255, null=True, verbose_name='关注列表'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fans',
            field=models.CharField(max_length=255, null=True, verbose_name='粉丝列表'),
        ),
    ]
