# Generated by Django 3.2.15 on 2022-08-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220828_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
